cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'
urlpatterns=[
    path('cart/', views.add_summary, name='add_summary'),
    path('add/', views.cart_add,name="cart_add"),
    path('delete/', views.cart_delete,name="cart_delete"),
    path('update/', views.cart_update,name="cart_update"),
      
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from core import settings
from django.conf.urls.static import static

#access urls in the settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),
    path('', include('cart.urls',namespace='cart')),
] 
# media url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:product_category_slug>/', views.product_category, name='product_category'),

]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse



# Create your models here.
class Category(models.Model):
    category_name=models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural='Categories'

    def get_absolute_url(self):
        return reverse('store:product_category', args=[self.slug])
        
    def __str__(self):
        return self.category_name



class Tags(models.Model):
    tag_name=models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural='Tags'


    def __str__(self):
        return self.tag_name




class Product (models.Model):
    category=models.ForeignKey(Category,related_name='product',on_delete=models.CASCADE)
    tag_name=models.ForeignKey(Tags,related_name='product',on_delete=models.CASCADE)
    product_name = models.CharField(max_length=200)
    slug=models.SlugField()
    short_description = models.TextField(blank=True)
    long_description = models.TextField(blank=True)
    featured_image= models.ImageField(upload_to='images/')
    other_image1= models.ImageField(upload_to='images/', blank=True, null=True)
    other_image2= models.ImageField(upload_to='images/',blank=True,null=True)
    other_image3= models.ImageField(upload_to='images/',blank=True,null=True)
    price = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    is_active =  models.BooleanField(default=True)
    created= models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name= 'Product'
        verbose_name_plural='Products'

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
    def __str__(self):
        return self.product_name

cart/views.py
#from django.http import  JsonResponse, request
import json
from django.http import response
from django.http.response import  JsonResponse
from django.shortcuts import get_object_or_404, render
from store.models import Product

from .cart import Cart


# Create your views here.
def add_summary(request):
    cart =Cart(request)
    print (cart)
    return render(request, 'cart/cart.html', {'cart':cart})

    # get product id when add to cart btn is clicked
def cart_add(request):
    cart = Cart(request)
    # first get session data from class Cart
    if request.POST.get('action')=='post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        # get product  id from the  whrn clicked

        product =  get_object_or_404(Product, id=product_id)
        # get product id from Product model
        cart.add(product = product ,qty = product_qty)
        # create class to add/save data
        baskettotalqty = cart.__len__()
        # capture total sum of qty when added to cart 

        
        response = JsonResponse({'qty':baskettotalqty,})
        return response


# Delete from session data
def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action')=='delete':
        product_id = int(request.POST.get('productid'))
        cart.delete(product = product_id)
        response = JsonResponse({'success':True})
        return response


#Update cart
def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action')=='update':
        product_id = int(request.POST.get('productid'))
        
        product_qty =str(request.POST.get('productqty'))

        #cart = cart.__len__()
        print(product_id)
        print(product_qty)
        response = JsonResponse({'Success':True})
        return response

store/views.py
from django.http import request
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# HOME PAGE
def index(request):
    products= Product.objects.all()
   
    return render(request, 'index.html',{'products':products,})
    
# SHOP PAGE
def shop(request):
    products= Product.objects.all()
   
    return render(request, 'shop.html',{'products':products,})

# PRODUCT DETAIL
def product_detail(request,slug):
   product = get_object_or_404(Product,slug=slug,in_stock=True)
   return render(request, 'product-details.html',{'product':product})






def product_category(request, product_category_slug,):
    categ = get_object_or_404(Category,slug = product_category_slug)
    products = Product.objects.filter(category=categ)
    return render (request, 'product-categories.html', {'productsCateg': products,'categ':categ })


def category(request,category_slug,):
    categ =get_object_or_404(Category,slug = category_slug)
    products = Product.objects.filter(category=categ) #filter from Product  - category model
    return render(request, 'store/products/categories.html',{'productCateg':products,'categ':categ})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">



<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="meta description">

    <!-- Site title -->
    <title>Huge variety - Mega Shop </title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font-Awesome CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- helper class css -->
    <link href="{% static 'css/helper.min.css' %}" rel="stylesheet">
    <!-- Plugins CSS -->
    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <!-- Main Style CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/skin-default.css' %}" rel="stylesheet" id="galio-skin">
</head>

<body>

<!-- navbar -->
{% include 'partials/_navbar.html' %}

{% block content %}
   

{% endblock  %}

{% include 'partials/_footer.html' %}


</body>

    <!--All jQuery, Third Party Plugins & Activation (main.js) Files-->
    <script src="{% static 'js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <!-- Jquery Min Js -->
    <script src="{% static 'js/vendor/jquery-3.3.1.min.js' %}"></script>
    <!-- Popper Min Js -->
    <script src="{% static 'js/vendor/popper.min.js' %}"></script>
    <!-- Bootstrap Min Js -->
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <!-- Plugins Js-->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Ajax Mail Js -->
    <script src="{% static 'js/ajax-mail.js' %}"></script>
    <!-- Active Js -->
    <script src="{% static 'js/main.js' %}"></script>
    <!-- Switcher JS [Please Remove this when Choose your Final Projct] -->
    <script src="{% static 'js/switcher.js' %}"></script>


    <script>
        //Add to cart
        $(document).on('click', '#add-button', function(e){



            //prevent  btn to fire off unless clicked
            e.preventDefault();
            
            $.ajax({
    
                type:'POST', 
                url:'{% url "cart:cart_add" %}', 
                
                data:{
                    //capture product id from btn
                    productid: $('#add-button').val(),
                    productqty:$('#qty-btn').val(),
                    //capture option  from  dropdown#
  
                    csrfmiddlewaretoken :"{{csrf_token}}",
                    action:'post',
    
                },
                
                success:function(json){
                document.getElementById("cart-qty").innerHTML=json.qty
                
                  //capture quantity when added
                },
                error: function(xhr,errmsg,err){}
            });
        });
    

        //Delete from cart

        $(document).on('click', '.delete-btn', function(e){



            //prevent  btn to fire off unless clicked
            e.preventDefault();
            var prod_id = $(this).data('index')
            // get prduct id when button is pressed

            $.ajax({
    
                type:'POST', 
                url:'{% url "cart:cart_delete" %}', 
                
                data:{
                    //capture product id from btn
                    productid: $(this).data('index'),
                    //capture option  from  dropdown#
  
                    csrfmiddlewaretoken :"{{csrf_token}}",
                    action:'delete',
    
                },
                
                success:function(json){
                    $('.product-item[data-index = "' + prod_id + '"]').remove();
                    //select product-item (div) to remove from selected id
                
                },
                error: function(xhr,errmsg,err){}
            });
        });




        
        //Update  cart

        $(document).on('click', '.update-btn', function(e){



            //prevent  btn to fire off unless clicked
            e.preventDefault();
            var prod_id = $(this).data('index')
            // get prduct id when button is pressed

            $.ajax({
    
                type:'POST', 
                url:'{% url "cart:cart_update" %}', 
                
                data:{
                    //capture product id from btn
                    productid: $(this).data('index'),
                    productqty: $('#number' + prod_id +  'option:selected' ).text(),
                    //capture option  from  dropdown#
  
                    csrfmiddlewaretoken :"{{csrf_token}}",
                    action:'update',
    
                },
                
                success:function(json){
                    //select product-item (div) to remove from selected id
                
                  //capture quantity when added
                },
                error: function(xhr,errmsg,err){}
            });
        });
    
  
    
    
    </script>
    

</body>



</html>

templates/cart/cart.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<body>

    <!-- color switcher start -->
  
    <!-- color switcher end -->

    <div class="wrapper box-layout">

        <!-- header area start -->
        <header>

            <!-- header top start -->
         
            <!-- header top end -->

            <!-- header middle start -->
         
            <!-- header middle end -->

            <!-- main menu area start -->
            
            <!-- main menu area end -->

        </header>
        <!-- header area end -->

        <!-- breadcrumb area start -->
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="breadcrumb-wrap">
                            <nav aria-label="breadcrumb">
                                <ul class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item"><a href="shop-grid-left-sidebar.html">shop</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">cart</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb area end -->

        <!-- cart main wrapper start -->
        <div class="cart-main-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Cart Table Area -->
                        <div class="cart-table table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th class="pro-thumbnail">Image</th>
                                    <th class="pro-title">Product name</th>
                                    <th class="pro-price">Price</th>
                                    <th class="pro-quantity">Quantity</th>
                                    <th class="pro-subtotal">Total</th>
                                    <th class="pro-subtotal">Update</th>
                                    <th class="pro-remove">Remove</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                    <!--loops through the products in the cart and displays them(only price and qty)-->
                                        {% with product=item.producttt %}
                                        <!-- goes through the loops that are merged and displays indidual products that are added to cart-->
                                            <tr data-index="{{product.id}}"  class="product-item">
                                                <td class="pro-thumbnail"><a href="{{product.get_absolute_url }}"><img class="img-fluid" src="{{product.featured_image.url}}"
                                                                                            alt="Product"/></a></td>
                                                <td class="pro-title"><a href="{{product.get_absolute_url }}">{{ product.product_name}}</a></td>
                                                <td class="pro-price"><span>ksh {{product.price}}</span></td>
                                                <td class="pro-quantity">
                                                    <select id="number">
                                                        <option selected>{{item.qty}}</option>
                                                        <option value="">1</option>
                                                        <option value="">2</option>
                                                        <option value="">3</option>
                                                        <option value="">4</option>
                                                    </select>
                                                </td>
                                                <td class="pro-subtotal"><span>ksh {{ item.total_price}}</span></td>
                                               
                                                <td class="pro-add"><button class="btn btn-success update-btn"  id="delete-btn" data-index="{{product.id}}"  value="" ><i class="fa fa-save"  ></button></td>

                                                <td class="pro-remove"><button class="btn btn-danger delete-btn"  id="delete-btn" data-index="{{product.id}}"  value="" ><i class="fa fa-trash-o"  ></button></td>
                                                    </tr>
                                            {% endwith %}
                                        {% endfor %}

                                
                                </tbody>
                            </table>
                        </div>
        
                        <!-- Cart Update Option -->
                        <div class="cart-update-option d-block d-md-flex justify-content-between">
                            <div class="apply-coupon-wrapper">
                                <form action="#" method="post" class=" d-block d-md-flex">
                                    <input type="text" placeholder="Enter Your Coupon Code" required />
                                    <button class="sqr-btn">Apply Coupon</button>
                                </form>
                            </div>
                            <div class="cart-update mt-sm-16">
                                <a href="#" class="sqr-btn">Update Cart</a>
                            </div>
                        </div>
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-lg-5 ml-auto">
                        <!-- Cart Calculation Area -->
                        <div class="cart-calculator-wrapper">
                            <div class="cart-calculate-items">
                                <h3>Cart Totals</h3>
                                <div class="table-responsive">
                                    <table class="table">
                                        
                                        <tr class="total">
                                            <td>Shipping fee</td>
                                            <td class="total-amount"> ksh 400</td>
                                        </tr>
                                       
                                        <tr class="total">
                                            <td>TOTAL PRICE</td>
                                            <td class="total-amount"> ksh {{cart.get_total_price}}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <a href="checkout.html" class="sqr-btn d-block">Proceed To Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- cart main wrapper end -->

        <!-- brand area start -->
        <div class="brand-area pt-34 pb-30">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mb-30">
                            <div class="title-icon">
                                <i class="fa fa-crop"></i>
                            </div>
                            <h3>Popular Brand</h3>
                        </div> <!-- section title end -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="brand-active slick-padding slick-arrow-style">
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br1.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br2.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br3.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br4.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br5.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br6.png" alt=""></a>
                            </div>
                            <div class="brand-item text-center">
                                <a href="#"><img src="assets/img/brand/br4.png" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- brand area end -->

        <!-- footer area start -->
        <footer>
            <!-- footer top start -->
            <div class="footer-top bg-black pt-14 pb-14">
                <div class="container">
                    <div class="footer-top-wrapper">
                        <div class="newsletter__wrap">
                            <div class="newsletter__title">
                                <div class="newsletter__icon">
                                    <i class="fa fa-envelope"></i>
                                </div>
                                <div class="newsletter__content">
                                    <h3>sign up for newsletter</h3>
                                    <p>Duis autem vel eum iriureDuis autem vel eum</p>
                                </div>
                            </div>
                            <div class="newsletter__box">
                                <form id="mc-form">
                                    <input type="email" id="mc-email" autocomplete="off" placeholder="Email">
                                    <button id="mc-submit">subscribe!</button>
                                </form>
                            </div>
                            <!-- mailchimp-alerts Start -->
                            <div class="mailchimp-alerts">
                                <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                                <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                                <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                            </div>
                            <!-- mailchimp-alerts end -->
                        </div>
                        <div class="social-icons">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Google-plus"><i class="fa fa-google-plus"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Youtube"><i class="fa fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- footer top end -->

        
        <!-- footer area end -->

    </div>

    <!-- Scroll to top start -->
    <div class="scroll-top not-visible">
        <i class="fa fa-angle-up"></i>
    </div>
    <!-- Scroll to Top End -->

    {% endblock %}